In [13]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import joblib

### Loading Dataset

In [14]:
df = pd.read_csv("datasets/creditcard_synthetic.csv")


### Selecting Features and Target

In [15]:
x = df.drop("Class", axis=1)
y = df["Class"]

### Classifiction Metrics

In [16]:
from sklearn.metrics import (
    classification_report,
    accuracy_score,
    # recall_score,
    # precision_score,
    # f1_score,
    confusion_matrix,
    roc_auc_score,
)

# from sklearn.metrics._plot.confusion_matrix import (
#     confusion_matrix,
# )


def print_metrics(y_true, y_pred):
    print("Classification Report: \n", classification_report(y_true, y_pred))
    print("Model Accuracy: ", accuracy_score(y_true, y_pred))
    print("ROC AUC: ", roc_auc_score(y_true, y_pred))
    print("Confusion matrix: \n", confusion_matrix(y_true, y_pred))

## Logistic Regression

In [17]:
model_lr = joblib.load("models/logistic_regression_model.joblib")

In [18]:
y_pred = model_lr.predict(x)

print_metrics(y, y_pred)

Classification Report: 
               precision    recall  f1-score   support

           0       0.81      0.65      0.72      1000
           1       0.71      0.85      0.77      1000

    accuracy                           0.75      2000
   macro avg       0.76      0.75      0.75      2000
weighted avg       0.76      0.75      0.75      2000

Model Accuracy:  0.752
ROC AUC:  0.752
Confusion matrix: 
 [[652 348]
 [148 852]]


## KNN

In [19]:
model_knn = joblib.load("models/knn_model.joblib")

In [20]:
y_pred = model_knn.predict(x)

print_metrics(y, y_pred)

Classification Report: 
               precision    recall  f1-score   support

           0       0.50      1.00      0.67      1000
           1       0.83      0.01      0.01      1000

    accuracy                           0.50      2000
   macro avg       0.67      0.50      0.34      2000
weighted avg       0.67      0.50      0.34      2000

Model Accuracy:  0.502
ROC AUC:  0.502
Confusion matrix: 
 [[999   1]
 [995   5]]


## Decision Tree Classifier

In [21]:
model_dtc = joblib.load("models/dtc_model.joblib")

In [22]:
y_pred = model_dtc.predict(x)

print_metrics(y, y_pred)

Classification Report: 
               precision    recall  f1-score   support

           0       0.51      0.97      0.67      1000
           1       0.66      0.06      0.10      1000

    accuracy                           0.51      2000
   macro avg       0.58      0.51      0.38      2000
weighted avg       0.58      0.51      0.38      2000

Model Accuracy:  0.5135
ROC AUC:  0.5135
Confusion matrix: 
 [[972  28]
 [945  55]]


## Random Forest

In [23]:
model_rfc = joblib.load("models/rfc_model.joblib")

In [24]:
y_pred = model_rfc.predict(x)

print_metrics(y, y_pred)

Classification Report: 
               precision    recall  f1-score   support

           0       0.50      1.00      0.67      1000
           1       0.00      0.00      0.00      1000

    accuracy                           0.50      2000
   macro avg       0.25      0.50      0.33      2000
weighted avg       0.25      0.50      0.33      2000

Model Accuracy:  0.5
ROC AUC:  0.5
Confusion matrix: 
 [[1000    0]
 [1000    0]]


/home/m/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/m/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/m/miniconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
